### ISSUE TITLE
spanish_la.json is not working smh

### ISSUE THREAD

**Issue by hearth1an** [Outer-Wilds-New-Horizons/new-horizons#424] opened 2022-10-17 16:23 UTC
### What Happened?

Idk why it's not working with The Vision (current [main](https://github.com/hearth1an/hearthian.TheVision) on github). All other languages works fine.

Errors:
![image](https://user-images.githubusercontent.com/106444732/196230955-df8c0d5a-be46-4a50-aa2f-b36e5ade3ee2.png)

**Comment by dgarroDC** [comment] 2022-10-18 04:05
I get the same log errors in another language I tried, French, is that language working?
![french](https://user-images.githubusercontent.com/22490080/196332777-b1a29e31-ca8a-44f9-910e-db68bfefdb6f.png)

**Comment by dgarroDC** [comment] 2022-10-18 06:06
Translations are not working on The Vision current main because this is failing:
![LoadAddonManifest  failure](https://user-images.githubusercontent.com/22490080/196347538-ed842c79-8150-49f1-8006-be67be46b879.png)

[`LoadAddonManifest` is done before `LoadTranslations`](https://github.com/Outer-Wilds-New-Horizons/new-horizons/blob/0f50c3dce9b23c085c2b920d15ab1e67eff68054/NewHorizons/Main.cs#L575), so if that fails then translations aren't loaded.

The issue is caused by this change:  https://github.com/hearth1an/hearthian.TheVision/commit/2ac24202e480557ebf72ea8f715ba02d4b19c656#diff-38aaec2d59eb3c8392c2f6451d8a9e18cf22c954102386f62f484f151d73a86eR56

I think it is a bug from OWML that is messing up the backslashes that you use in `\"The Vision\"`. When it tries to deserialize the the addon manifest JSON in `mod.ModHelper.Storage.Load<AddonConfig>(file);` it returns `null` for some reason.

As a workaround you could use this:
`'Thank you for playing "The Vision"!'` (instead of `"Thank you for playing \"The Vision\"!"`)
That way you can avoid the backslashes but still display the `"The Vision"` text.

**Comment by dgarroDC** [comment] 2022-10-20 03:37
Fixed in 15c73d3339ba0e0440e47cd805245a3215a97492

**Closed by dgarroDC** 2022-10-20 03:37 UTC
Labels: bug
