### ISSUE TITLE
Starting popup does not appear

### ISSUE THREAD

**Issue by 2walker2** [Outer-Wilds-New-Horizons/new-horizons#402] opened 2022-09-26 15:17 UTC
### What Happened?

The starting popup specified in manifest.json does not appear. Tested both by deleting New Horizons save.json and by downloading the mod onto a computer that had never run the mod before. No errors appeared in the console. Attached addon-manifest.json (with file extension changed to .txt to allow for uploading).

[addon-manifest.txt](https://github.com/Outer-Wilds-New-Horizons/new-horizons/files/9647477/addon-manifest.txt)

### What was supposed to happen?

The starting popup should have appeared on launch.

### Platform

Steam

### Mods

```Markdown
Outer Wilds Mod Manager
OWML
New Horizons
Menu Framework
Vanilla Fix
Cheat and Debug Menu
Common Camera Utility
Unity Explorer
Astral Codex (the mod for which the popup should have appeared)
```

### Logs

```Shell
No errors in console
```

**Comment by xen-42** [comment] 2022-10-01 02:13
Do the credits work? To see if its the entire addon manifest or not

**Comment by xen-42** [comment] 2022-10-01 04:22
Turns out this is actually a bug caused by Vanilla Fix, and will be fixed in that instead.

**Comment by xen-42** [comment] 2022-10-01 04:23
Not "completed" because its not going to be fixed in NH so

**Closed by xen-42** 2022-10-01 04:22 UTC
Labels: bug
