### ISSUE TITLE
Slide Reel Optimization 

### ISSUE THREAD

**Issue by pikpik-carrot** [Outer-Wilds-New-Horizons/new-horizons#999] opened 2024-12-07 23:03 UTC
### What Happened?

With Eyes of the Past, the amount of slide reels it has causes Outer Wilds to crash when I try to open it due to memory issues

### What was supposed to happen?

...it not crashing

### Platform

None

**Comment by JohnCorby** [comment] 2024-12-08 00:00
duplicate of #898

**Closed by JohnCorby** 2024-12-08 00:00 UTC
Labels: bug
