### ISSUE TITLE
Scaled bramble nodes looks too shiny with proxy model

### ISSUE THREAD

**Issue by hearth1an** [Outer-Wilds-New-Horizons/new-horizons#641] opened 2023-07-16 17:44 UTC
### What Happened?

![image](https://github.com/Outer-Wilds-New-Horizons/new-horizons/assets/106444732/ef16c965-721d-48e2-a6ff-c69c9e57661e)

### What was supposed to happen?

It looks okay when getting closer

### Platform

None

### Mods

```Markdown
Origins
```

**Comment by xen-42** [comment] 2023-07-17 17:41
@hearth1an how far away from it are you when it happens? Could you also provide images of what it is supposed to look like

**Comment by hearth1an** [comment] 2023-07-17 20:57
I can see this from TH.
![image](https://github.com/Outer-Wilds-New-Horizons/new-horizons/assets/106444732/07b7d33c-306c-41ae-a45b-e7d83014f3f6)

**Comment by hearth1an** [comment] 2023-07-17 20:58
That's how it looks when I'm getting closer 
![image](https://github.com/Outer-Wilds-New-Horizons/new-horizons/assets/106444732/ef72e2d1-cd3a-430b-b374-163b67726706)

**Comment by hearth1an** [comment] 2023-07-17 21:01
Here's the object I can disable to make it look nice again
![image](https://github.com/Outer-Wilds-New-Horizons/new-horizons/assets/106444732/9aabbfca-be89-426e-885c-6d231bb1dee0)

**Comment by hearth1an** [comment] 2023-07-17 21:03
but then DB looks goofy with no fog sphere
![image](https://github.com/Outer-Wilds-New-Horizons/new-horizons/assets/106444732/ad779f24-2cc4-4605-999c-f5c3541c6fb3)

**Comment by xen-42** [comment] 2023-07-18 04:09
when does this happen in your mod? I just loaded in with it and there was nothing

**Comment by hearth1an** [comment] 2023-07-18 04:10
It's active once you learn the frequency from quantum moon

**Comment by JohnCorby** [comment] 2023-07-20 00:04
didnt you fix this in the Origins update? how?

**Comment by hearth1an** [comment] 2023-07-20 04:56
well if disabling the lod at all counts as fix so yeah

**Comment by JohnCorby** [comment] 2023-07-20 23:13
oh.

**Comment by JohnCorby** [comment] 2023-07-22 06:38
qskill issue

**Comment by xen-42** [comment] 2023-08-23 16:20
Assigning to clay because he made bramble nodes

**Comment by xen-42** [comment] 2023-08-26 06:23
Mfw this was a duplicate of #372 so it's fixed in dev now.

**Closed** 2023-08-26 06:55 UTC
Labels: bug, fixed in dev
