### ISSUE TITLE
time loop still happens when warping with vessel

### ISSUE THREAD

**Issue by AnonymousStrangerOW** [Outer-Wilds-New-Horizons/new-horizons#961] opened 2024-10-07 22:34 UTC
### What Happened?

i warped to the vessel, opened cheats and debug's clock with the tilde (~) key, and noticed the clock was still counting down to the end of the loop.

### What was supposed to happen?

the clock should be static or at least identical to the eye's output (starting from 0:00 and going into negatives), and the time loop shouldn't be happening.
![image](https://github.com/user-attachments/assets/c764fb19-f779-4237-8b67-88ffd4247549)

### Platform

Steam

### Mods

```Markdown
"_nebula.MenuFramework",
  "Locochoco.ColliderVisualizer",
  "AnonymousStrangerOW.TheStrangerTheyAre",
  "Glitch.AltDebugMenu",
  "Anyar.CustomAnglerfishAI",
  "Bwc9876.SaveEditor",
  "Vesper.UnityExplorer",
  "xen.CommonCameraUtility",
  "JohnCorby.VanillaFix",
  "JohnCorby.OWFixPluginTypesSerialization",
  "Switch.BringMeMyShip",
  "dgarro.CustomShipLogModes",
  "misternebula.FreeCam",
  "Bwc9876.TimeSaver",
  "VioVayo.DWModAssist",
  "dgarro.SuitLog",
  "xen.NewHorizons",
  "xen.EyeHelper",
  "Alek.LightBramble"
```

**Comment by MegaPiggy** [comment] 2024-10-07 22:37
what does this mean?

**Comment by AnonymousStrangerOW** [comment] 2024-10-07 22:49
added it there too, but it's supposed to be a continuation of https://github.com/Outer-Wilds-New-Horizons/new-horizons/issues/952 which already closed.

**Comment by xen-42** [comment] 2024-10-07 23:12
The clock must still count down. Else removing the AWC would break all time-related events (sand rising, funnels).

So the clock thing is fine and expected. Please provide proof that the time loop is still happening if that is the case, since that would be its own issue.

**Comment by xen-42** [comment] 2024-10-14 03:57
I'm closing this since the description of what the "bug" is is not a bug. If you find that the time loop actually happens after warping, then you can re-open this.

**Closed by xen-42** 2024-10-14 03:57 UTC
Labels: bug
